// Full 78-card tarot deck with concise, genuine upright/reversed meanings.
// Used by the interactive Tarot Reading tool. Rider–Waite–Smith tradition.
// Each card: { name, arcana, upKw, up, revKw, rev }

export const TAROT = [
  // ── Major Arcana (22) ──
  { name: 'The Fool', arcana: 'Major Arcana', upKw: 'New beginnings, spontaneity, a leap of faith', up: 'A fresh chapter is opening. Trust the pull of something new and take the first step even without every answer.', revKw: 'Recklessness, hesitation, fear of the unknown', rev: 'You may be leaping without looking — or frozen at the edge. Pause to plan, then move with intention.' },
  { name: 'The Magician', arcana: 'Major Arcana', upKw: 'Manifestation, willpower, resourcefulness', up: 'You have everything you need to make it happen. Focus your intention and act — the tools are already in your hands.', revKw: 'Manipulation, untapped talent, self-doubt', rev: 'Your power is scattered or misused. Realign your actions with honest intentions and use your gifts.' },
  { name: 'The High Priestess', arcana: 'Major Arcana', upKw: 'Intuition, mystery, the subconscious', up: 'The answer is quieter than logic. Go inward, trust your gut, and let the hidden become clear in its own time.', revKw: 'Secrets withheld, ignoring your inner voice', rev: 'You may be talking over your intuition. Get quiet and listen to what you already sense but keep dismissing.' },
  { name: 'The Empress', arcana: 'Major Arcana', upKw: 'Abundance, nurturing, creativity', up: 'A season of growth and care. Nurture what you love — a project, a bond, yourself — and let it flourish.', revKw: 'Creative block, dependence, self-neglect', rev: 'You may be pouring out with nothing coming back. Refill your own cup before giving more.' },
  { name: 'The Emperor', arcana: 'Major Arcana', upKw: 'Structure, authority, stability', up: 'Build the framework. Discipline, boundaries, and a steady plan turn ambition into something that lasts.', revKw: 'Control, rigidity, domination', rev: 'Structure has hardened into control. Loosen the grip and allow some flexibility back in.' },
  { name: 'The Hierophant', arcana: 'Major Arcana', upKw: 'Tradition, guidance, shared belief', up: 'Wisdom from mentors, tradition, or community is worth leaning on now. Seek proven guidance.', revKw: 'Rebellion, questioning norms, your own path', rev: 'The old rules may not fit anymore. It is okay to question the script and find your own way.' },
  { name: 'The Lovers', arcana: 'Major Arcana', upKw: 'Love, harmony, meaningful choices', up: 'A deep connection or an important choice guided by your values. Lead with the heart and be honest.', revKw: 'Disharmony, imbalance, misaligned values', rev: 'Something is out of alignment — in a relationship or within yourself. Get clear on what you truly value.' },
  { name: 'The Chariot', arcana: 'Major Arcana', upKw: 'Determination, willpower, victory', up: 'Focus and drive carry you forward. Hold your direction and push — you can win this through sheer will.', revKw: 'Loss of control, lack of direction', rev: 'You are being pulled in two directions. Regain focus and decide where you are actually going.' },
  { name: 'Strength', arcana: 'Major Arcana', upKw: 'Courage, inner strength, patience', up: 'Real strength is gentle. Meet the challenge with calm, patience, and quiet courage rather than force.', revKw: 'Self-doubt, raw emotion, low confidence', rev: 'Fear or frustration has the upper hand. Be tender with yourself and rebuild your inner steadiness.' },
  { name: 'The Hermit', arcana: 'Major Arcana', upKw: 'Introspection, solitude, inner guidance', up: 'Step back from the noise. The answers you need come from reflection and time alone with your thoughts.', revKw: 'Isolation, loneliness, withdrawal', rev: 'Solitude has tipped into isolation. Reach back out — connection is part of the answer too.' },
  { name: 'Wheel of Fortune', arcana: 'Major Arcana', upKw: 'Change, cycles, turning points', up: 'The wheel is turning in your favor. A shift in luck or circumstance is arriving — stay open to it.', revKw: 'Bad luck, resistance to change', rev: 'You are fighting a cycle you cannot control. Loosen your grip and let the turn happen.' },
  { name: 'Justice', arcana: 'Major Arcana', upKw: 'Fairness, truth, accountability', up: 'Truth and cause-and-effect are at work. Act with integrity and things will balance out fairly.', revKw: 'Injustice, dishonesty, avoiding consequences', rev: 'Something feels unfair or unaccounted for. Face the truth honestly rather than dodging it.' },
  { name: 'The Hanged Man', arcana: 'Major Arcana', upKw: 'Surrender, new perspective, pause', up: 'Stop forcing it. A pause and a change of viewpoint will show you what pushing never could.', revKw: 'Stalling, indecision, resistance', rev: 'You are stuck in limbo, resisting the pause. Let go of the need to control the outcome.' },
  { name: 'Death', arcana: 'Major Arcana', upKw: 'Endings, transformation, letting go', up: 'Not literal — a chapter is ending so a truer one can begin. Release what is over and let it transform you.', revKw: 'Clinging to the past, fear of change', rev: 'You are holding onto something already finished. The discomfort is the ending asking to complete.' },
  { name: 'Temperance', arcana: 'Major Arcana', upKw: 'Balance, moderation, patience', up: 'Blend the extremes. Patience, moderation, and a steady middle path bring things into harmony.', revKw: 'Excess, imbalance, impatience', rev: 'Something is out of proportion. Slow down and find the balance you have been skipping past.' },
  { name: 'The Devil', arcana: 'Major Arcana', upKw: 'Attachment, temptation, feeling trapped', up: 'Notice what has a hold on you — a habit, a fear, a dynamic. The chains are looser than they feel.', revKw: 'Breaking free, reclaiming power', rev: 'You are waking up to an unhealthy attachment and starting to break free. Keep going.' },
  { name: 'The Tower', arcana: 'Major Arcana', upKw: 'Sudden upheaval, revelation, awakening', up: 'A sudden shake-up clears away what was built on shaky ground. Painful, but it frees you for truth.', revKw: 'Avoiding disaster, fear of change', rev: 'You may be bracing for or delaying an inevitable shift. Better to let the false thing fall.' },
  { name: 'The Star', arcana: 'Major Arcana', upKw: 'Hope, renewal, faith', up: 'After the storm, calm and hope return. Heal gently and trust that things are realigning for you.', revKw: 'Hopelessness, disconnection, doubt', rev: 'Faith feels thin right now. Reconnect with what quietly renews you and let hope back in.' },
  { name: 'The Moon', arcana: 'Major Arcana', upKw: 'Illusion, intuition, the unknown', up: 'Things are not fully clear yet. Trust your intuition through the fog and do not mistake fear for fact.', revKw: 'Releasing fear, confusion clearing', rev: 'The fog is lifting and anxieties are losing their grip. Truth is coming into view.' },
  { name: 'The Sun', arcana: 'Major Arcana', upKw: 'Joy, success, vitality', up: 'A bright, warm card — success, clarity, and genuine joy. Let yourself enjoy the good that is here.', revKw: 'Temporary gloom, delayed happiness', rev: 'The sun is behind a cloud, not gone. A brighter moment is closer than it feels.' },
  { name: 'Judgement', arcana: 'Major Arcana', upKw: 'Reckoning, renewal, awakening', up: 'A moment of clarity calls you to rise into a truer version of yourself. Answer it honestly.', revKw: 'Self-doubt, avoiding the call', rev: 'You may be ignoring an inner call or judging yourself harshly. Forgive, then step forward.' },
  { name: 'The World', arcana: 'Major Arcana', upKw: 'Completion, achievement, wholeness', up: 'A cycle completes with a sense of wholeness. Celebrate how far you have come — then begin anew.', revKw: 'Incompletion, loose ends', rev: 'You are close, but something is unfinished. Tie up the loose end to truly close the chapter.' },

  // ── Wands (Fire — passion, energy, action) ──
  { name: 'Ace of Wands', arcana: 'Wands', upKw: 'Inspiration, new energy, a spark', up: 'A creative spark or fresh passion ignites. Act on the excitement while the energy is hot.', revKw: 'Delays, lack of direction', rev: 'The spark is there but stalling. Clarify what you actually want, then light it.' },
  { name: 'Two of Wands', arcana: 'Wands', upKw: 'Planning, vision, decisions', up: 'You are surveying the horizon and planning your next move. Dream bigger and commit to a direction.', revKw: 'Fear of the unknown, playing it safe', rev: 'Comfort is holding you back from a bolder path. Do not shrink the plan out of fear.' },
  { name: 'Three of Wands', arcana: 'Wands', upKw: 'Expansion, foresight, progress', up: 'Your efforts are gaining momentum and horizons are widening. Keep looking forward — growth is coming.', revKw: 'Delays, obstacles, playing small', rev: 'Progress feels blocked or your vision too narrow. Widen the lens and be patient with setbacks.' },
  { name: 'Four of Wands', arcana: 'Wands', upKw: 'Celebration, home, harmony', up: 'A joyful milestone, stability, and belonging. Pause to celebrate what you have built with others.', revKw: 'Instability, lack of support, transition', rev: 'The foundation feels shaky or a celebration is delayed. Tend to what makes you feel at home.' },
  { name: 'Five of Wands', arcana: 'Wands', upKw: 'Competition, conflict, tension', up: 'Friction and clashing energies. A bit of healthy competition can sharpen you — pick your battles.', revKw: 'Avoiding conflict, finding resolution', rev: 'Tension is easing, or you are sidestepping a needed conversation. Address it and move to peace.' },
  { name: 'Six of Wands', arcana: 'Wands', upKw: 'Victory, recognition, confidence', up: 'Success and well-earned recognition. Walk tall — your effort is being seen and rewarded.', revKw: 'Lack of recognition, self-doubt', rev: 'You may feel overlooked or unsure of a win. Validate yourself before seeking it outside.' },
  { name: 'Seven of Wands', arcana: 'Wands', upKw: 'Defense, perseverance, standing firm', up: 'Hold your ground. You have the high position — defend what you have built and stay the course.', revKw: 'Overwhelm, giving up', rev: 'The constant defending is wearing you down. Choose which fights are truly worth it.' },
  { name: 'Eight of Wands', arcana: 'Wands', upKw: 'Speed, movement, swift action', up: 'Things are moving fast — messages, momentum, quick developments. Ride the wave and act promptly.', revKw: 'Delays, frustration, slowing down', rev: 'Momentum has stalled and patience is thin. Wait out the delay rather than forcing it.' },
  { name: 'Nine of Wands', arcana: 'Wands', upKw: 'Resilience, persistence, almost there', up: 'You are tired but close. One more push — your resilience is exactly what carries you over the line.', revKw: 'Exhaustion, defensiveness', rev: 'You are running on empty and guarded. Rest, then decide what is still worth defending.' },
  { name: 'Ten of Wands', arcana: 'Wands', upKw: 'Burden, responsibility, hard work', up: 'You are carrying a lot. The goal is near, but check whether every burden is truly yours to hold.', revKw: 'Releasing burdens, delegating', rev: 'It is time to put something down or ask for help. You were not meant to carry it all alone.' },
  { name: 'Page of Wands', arcana: 'Wands', upKw: 'Curiosity, enthusiasm, exploration', up: 'A spark of curiosity and eagerness to explore. Follow the excitement and try the new thing.', revKw: 'Scattered energy, hesitation', rev: 'Enthusiasm is unfocused or stalling. Pick one direction and give it real energy.' },
  { name: 'Knight of Wands', arcana: 'Wands', upKw: 'Adventure, passion, boldness', up: 'Bold, passionate, ready to charge. Channel the fire into action — just aim before you leap.', revKw: 'Recklessness, impulsiveness', rev: 'The fire is burning too hot. Slow down before impulse leads you somewhere you did not intend.' },
  { name: 'Queen of Wands', arcana: 'Wands', upKw: 'Confidence, warmth, magnetism', up: 'Radiant, self-assured, magnetic. Own your presence and let your warmth draw the right things to you.', revKw: 'Self-doubt, insecurity', rev: 'Confidence is wobbling. Reconnect with what makes you feel vibrant and sure of yourself.' },
  { name: 'King of Wands', arcana: 'Wands', upKw: 'Leadership, vision, boldness', up: 'A natural, visionary leader. Set the direction with conviction and inspire others to follow.', revKw: 'Impulsiveness, domineering', rev: 'Leadership has tipped into control or haste. Lead with vision, not force.' },

  // ── Cups (Water — emotion, love, relationships) ──
  { name: 'Ace of Cups', arcana: 'Cups', upKw: 'New love, emotion, compassion', up: 'The heart opens — new love, deep feeling, or emotional renewal. Let yourself receive it.', revKw: 'Blocked feelings, emptiness', rev: 'Emotions feel shut off or drained. Give yourself permission to feel and refill from within.' },
  { name: 'Two of Cups', arcana: 'Cups', upKw: 'Connection, partnership, attraction', up: 'A meaningful, mutual bond — romance, friendship, or a true meeting of hearts. Honor the connection.', revKw: 'Imbalance, tension, a break', rev: 'A connection is out of balance. Have the honest talk before resentment sets in.' },
  { name: 'Three of Cups', arcana: 'Cups', upKw: 'Friendship, celebration, community', up: 'Joy shared with your people. Celebrate, lean on your circle, and let yourself belong.', revKw: 'Overindulgence, isolation', rev: 'Too much of a good thing, or feeling left out. Seek genuine connection over surface fun.' },
  { name: 'Four of Cups', arcana: 'Cups', upKw: 'Apathy, contemplation, missed offers', up: 'You may be so focused on what is missing that you overlook a gift already extended. Look up.', revKw: 'New awareness, accepting an offer', rev: 'You are coming out of the fog and ready to say yes to something you had ignored.' },
  { name: 'Five of Cups', arcana: 'Cups', upKw: 'Loss, grief, disappointment', up: 'Grief over what did not work out is valid — but two cups still stand. Do not miss what remains.', revKw: 'Acceptance, moving on', rev: 'You are making peace with a loss and turning toward what is still here. Healing is underway.' },
  { name: 'Six of Cups', arcana: 'Cups', upKw: 'Nostalgia, memories, innocence', up: 'Warm nostalgia or a return of something familiar. Let sweetness and simple kindness back in.', revKw: 'Stuck in the past, letting go', rev: 'Living in memory is keeping you from now. Honor the past, then step into the present.' },
  { name: 'Seven of Cups', arcana: 'Cups', upKw: 'Choices, fantasy, illusion', up: 'Many tempting options, not all real. Dream, but then get honest about which choice has substance.', revKw: 'Clarity, focus, decision', rev: 'The illusions clear and you can finally choose. Commit to what is actually right for you.' },
  { name: 'Eight of Cups', arcana: 'Cups', upKw: 'Walking away, seeking more', up: 'You are ready to leave behind what no longer fulfills you and seek something deeper. Trust the pull.', revKw: 'Fear of change, aimlessness', rev: 'You sense you should move on but fear or drift holds you. Name what you are really seeking.' },
  { name: 'Nine of Cups', arcana: 'Cups', upKw: 'Contentment, wishes fulfilled', up: 'The "wish card" — satisfaction and emotional fulfillment. Savor it and feel genuine gratitude.', revKw: 'Dissatisfaction, seeking more', rev: 'You got what you wanted but it feels hollow. Look at what would truly satisfy you.' },
  { name: 'Ten of Cups', arcana: 'Cups', upKw: 'Harmony, happiness, belonging', up: 'Emotional fulfillment with the people who matter — love, family, home. This is the good stuff.', revKw: 'Disconnection, broken bonds', rev: 'A gap between the picture and the feeling. Tend to the relationships that need real repair.' },
  { name: 'Page of Cups', arcana: 'Cups', upKw: 'Creativity, intuition, sweet surprises', up: 'A gentle, imaginative message or a tender new feeling. Stay open to whimsy and your inner voice.', revKw: 'Emotional immaturity, blocked creativity', rev: 'Feelings or creativity feel stuck or overly sensitive. Be patient and let them flow again.' },
  { name: 'Knight of Cups', arcana: 'Cups', upKw: 'Romance, charm, following the heart', up: 'A romantic, heartfelt invitation or gesture. Lead with feeling — but keep one foot on the ground.', revKw: 'Moodiness, unrealistic ideals', rev: 'Idealizing or moody swings cloud the picture. Separate the fantasy from the real person.' },
  { name: 'Queen of Cups', arcana: 'Cups', upKw: 'Compassion, empathy, emotional security', up: 'Deeply caring and intuitive. Nurture others from a full, secure place — and include yourself.', revKw: 'Over-sensitivity, self-neglect', rev: 'You may be absorbing everyone else’s feelings. Protect your own emotional energy.' },
  { name: 'King of Cups', arcana: 'Cups', upKw: 'Emotional balance, calm, diplomacy', up: 'Mastery of feeling — calm, wise, and kind under pressure. Lead with a steady, compassionate heart.', revKw: 'Emotional manipulation, moodiness', rev: 'Emotions are being suppressed or used to control. Return to honest, balanced feeling.' },

  // ── Swords (Air — thought, truth, conflict) ──
  { name: 'Ace of Swords', arcana: 'Swords', upKw: 'Clarity, truth, breakthrough', up: 'A mental breakthrough cuts through confusion. See the truth clearly and act on it decisively.', revKw: 'Confusion, clouded judgment', rev: 'Clarity is missing or the truth is muddied. Gather facts before you decide.' },
  { name: 'Two of Swords', arcana: 'Swords', upKw: 'Difficult choice, stalemate', up: 'A hard decision you have been avoiding by looking away. Take off the blindfold and face it.', revKw: 'Indecision, information overload', rev: 'Stuck between options and overwhelmed. Clear the noise and trust yourself to choose.' },
  { name: 'Three of Swords', arcana: 'Swords', upKw: 'Heartbreak, sorrow, painful truth', up: 'Pain or a hard truth pierces the heart. Let yourself grieve — clarity and healing follow honesty.', revKw: 'Recovery, forgiveness, release', rev: 'You are moving through the hurt and beginning to release it. The worst of the pain is passing.' },
  { name: 'Four of Swords', arcana: 'Swords', upKw: 'Rest, recovery, contemplation', up: 'Pause and recover. Rest is not quitting — it is what lets you return clear and strong.', revKw: 'Restlessness, burnout', rev: 'You are pushing past your limits. Stop and truly rest before you run out entirely.' },
  { name: 'Five of Swords', arcana: 'Swords', upKw: 'Conflict, winning at a cost', up: 'A conflict where "winning" may cost more than it gives. Ask whether being right is worth it.', revKw: 'Reconciliation, moving on', rev: 'You are ready to put down the sword and make peace. Choose resolution over pride.' },
  { name: 'Six of Swords', arcana: 'Swords', upKw: 'Transition, moving on, calmer waters', up: 'Leaving turbulence behind for something calmer. The journey is worth it — keep moving toward peace.', revKw: 'Resistance, unfinished business', rev: 'Something keeps pulling you back. Address what is unresolved so you can fully move on.' },
  { name: 'Seven of Swords', arcana: 'Swords', upKw: 'Strategy, deception, acting alone', up: 'A time for cleverness and going your own way — but be honest with yourself about your motives.', revKw: 'Coming clean, conscience', rev: 'A secret or half-truth wants to surface. Honesty will lift a weight you have been carrying.' },
  { name: 'Eight of Swords', arcana: 'Swords', upKw: 'Feeling trapped, self-limitation', up: 'The trap feels total, but the binding is largely in the mind. Look — a way out is right there.', revKw: 'Freeing yourself, new perspective', rev: 'You are realizing the cage was never locked. Step out and reclaim your freedom.' },
  { name: 'Nine of Swords', arcana: 'Swords', upKw: 'Anxiety, worry, sleepless nights', up: 'The 3 a.m. worries feel enormous. Most of this fear is not fact — name it and it loses power.', revKw: 'Releasing fear, hope returning', rev: 'The anxiety is loosening its grip. Reach for support and let the light back in.' },
  { name: 'Ten of Swords', arcana: 'Swords', upKw: 'Painful ending, rock bottom', up: 'A definitive, painful ending — but it truly is the bottom, which means the only way now is up.', revKw: 'Recovery, the worst is over', rev: 'You are rising from a low point. The hardest part is behind you; recovery begins.' },
  { name: 'Page of Swords', arcana: 'Swords', upKw: 'Curiosity, new ideas, vigilance', up: 'A sharp, curious mind and fresh ideas. Ask questions, stay alert, and speak your truth.', revKw: 'Scattered thoughts, gossip', rev: 'Mental energy is scattered or caught in gossip. Focus and think before you speak.' },
  { name: 'Knight of Swords', arcana: 'Swords', upKw: 'Ambition, drive, fast action', up: 'Charging ahead with focus and force. Great for cutting through — just aim before you swing.', revKw: 'Impatience, recklessness', rev: 'All speed, no steering. Slow the charge before it causes damage you did not intend.' },
  { name: 'Queen of Swords', arcana: 'Swords', upKw: 'Clarity, honesty, independence', up: 'Clear-eyed, honest, and independent. Cut through the noise with truth and healthy boundaries.', revKw: 'Coldness, harsh judgment', rev: 'Clarity has hardened into coldness. Temper honesty with a little warmth.' },
  { name: 'King of Swords', arcana: 'Swords', upKw: 'Intellect, authority, truth', up: 'Clear judgment and principled authority. Decide with logic, fairness, and unflinching honesty.', revKw: 'Manipulation, cold logic', rev: 'Intellect used to control or dismiss feeling. Return to fair, humane reasoning.' },

  // ── Pentacles (Earth — money, work, body, home) ──
  { name: 'Ace of Pentacles', arcana: 'Pentacles', upKw: 'Opportunity, prosperity, new venture', up: 'A solid new opportunity — money, work, or a tangible fresh start. Plant the seed and tend it.', revKw: 'Lost opportunity, scarcity mindset', rev: 'A chance may slip or fear of lack holds you back. Shift from scarcity to possibility.' },
  { name: 'Two of Pentacles', arcana: 'Pentacles', upKw: 'Balance, adaptability, juggling', up: 'Juggling multiple demands with agility. Stay flexible and prioritize to keep it all afloat.', revKw: 'Overwhelm, disorganization', rev: 'Too many balls in the air. Drop what does not matter and get organized before you drop what does.' },
  { name: 'Three of Pentacles', arcana: 'Pentacles', upKw: 'Teamwork, skill, collaboration', up: 'Good work built with others. Combine your skill with collaboration and the result rises.', revKw: 'Lack of teamwork, poor quality', rev: 'Misaligned effort or cut corners. Get everyone on the same page and do it properly.' },
  { name: 'Four of Pentacles', arcana: 'Pentacles', upKw: 'Security, saving, holding on', up: 'Building stability and holding onto what you have. Security is good — just do not grip too tightly.', revKw: 'Greed, holding too tightly, letting go', rev: 'Fear has you clutching too hard. Loosen up — some flow serves you better than a white-knuckle hold.' },
  { name: 'Five of Pentacles', arcana: 'Pentacles', upKw: 'Hardship, insecurity, worry', up: 'A lean or lonely stretch. Help is nearer than it looks — do not be too proud to seek it.', revKw: 'Recovery, help arriving', rev: 'You are coming out of a hard patch. Support and stability are returning.' },
  { name: 'Six of Pentacles', arcana: 'Pentacles', upKw: 'Generosity, give and receive', up: 'A healthy flow of giving and receiving. Share what you have, and let yourself accept help too.', revKw: 'Strings attached, inequality', rev: 'Generosity with conditions, or an unfair exchange. Restore honest balance in giving and taking.' },
  { name: 'Seven of Pentacles', arcana: 'Pentacles', upKw: 'Patience, long-term view, investment', up: 'Your efforts are growing but not ripe yet. Be patient — this is a long game worth the wait.', revKw: 'Impatience, poor return', rev: 'Frustration with slow results. Reassess whether to keep investing or redirect your energy.' },
  { name: 'Eight of Pentacles', arcana: 'Pentacles', upKw: 'Mastery, diligence, skill-building', up: 'Heads-down craftsmanship. Keep refining your skill — this is how expertise and quality are built.', revKw: 'Perfectionism, uninspired work', rev: 'Effort feels rote or overly perfectionist. Reconnect with why the work matters.' },
  { name: 'Nine of Pentacles', arcana: 'Pentacles', upKw: 'Abundance, self-sufficiency, luxury', up: 'Independent, comfortable, and enjoying the fruits of your effort. Savor your well-earned ease.', revKw: 'Over-reliance, setback', rev: 'A financial wobble or leaning too hard on others. Rebuild your own footing.' },
  { name: 'Ten of Pentacles', arcana: 'Pentacles', upKw: 'Legacy, wealth, family stability', up: 'Lasting security and something built to outlive you — family, legacy, deep-rooted stability.', revKw: 'Financial loss, instability', rev: 'The long-term foundation feels shaky. Tend to the roots — security and family bonds.' },
  { name: 'Page of Pentacles', arcana: 'Pentacles', upKw: 'Ambition, study, new opportunity', up: 'A grounded new goal or chance to learn. Study it, plan it, and take the practical first step.', revKw: 'Procrastination, missed chances', rev: 'Good ideas going nowhere. Stop stalling and act on the opportunity in front of you.' },
  { name: 'Knight of Pentacles', arcana: 'Pentacles', upKw: 'Reliability, hard work, routine', up: 'Steady, dependable, methodical. Slow and consistent effort gets you all the way there.', revKw: 'Stagnation, boredom', rev: 'Routine has become a rut. Add a spark so reliability does not curdle into stagnation.' },
  { name: 'Queen of Pentacles', arcana: 'Pentacles', upKw: 'Nurturing, practical, abundant', up: 'Warm, capable, and grounded — caring for others while keeping life running. Include your own needs.', revKw: 'Self-neglect, work-life imbalance', rev: 'You are giving so much that your own well is running dry. Rebalance and care for yourself.' },
  { name: 'King of Pentacles', arcana: 'Pentacles', upKw: 'Wealth, security, leadership', up: 'Abundant, stable, and generous with it. You have built something solid — lead and provide wisely.', revKw: 'Greed, materialism, control', rev: 'Security has curdled into greed or control. Remember what the wealth is actually for.' },
];

export function drawCards(n) {
  const idx = [...Array(TAROT.length).keys()];
  for (let i = idx.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [idx[i], idx[j]] = [idx[j], idx[i]];
  }
  return idx.slice(0, n).map((i) => ({
    ...TAROT[i],
    reversed: Math.random() < 0.4,
  }));
}
